apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: web
      containers:
      - image: gcr.io/PROJECT_ID/IMAGE:TAG
        name: web
